add header stucture
O-TYSHCHENKO/food-sta-tp pull request #6
Opened 2023-03-26 13:24 UTC by kondyan2022

Attention!!! Make auto-formatting the same for everyone. 
Доброго дня. Нужно сделать автоформатирование у всех одинаковым. Иначе будет казаться, что кто-то, не в своем модуле что-то менял. Как вариант: файл настроек  Нужен  .prettierrc.json в проект, который установит одинаковые настройки. Например такого содержания: 
{
  "printWidth": 80,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "trailingComma": "es5",
  "bracketSpacing": true,
  "bracketSameLine": false,
  "arrowParens": "avoid",
  "proseWrap": "always"
}

2023-03-26 14:07 UTC, O-TYSHCHENKO commented
Мне сложно дать оценку этому предложению, но наверняка идея отличная! 
Предлагаю пока исходить из того, что мы не знаем такой подход и пробовать добавлять коммиты по примеру ментора. Если будут явные проблемы - будем пробовать применять .prettierrc.json или иные варианты.

2023-03-26 14:09 UTC, O-TYSHCHENKO approved these changes

2023-03-26 14:57 UTC, kondyan2022 commented
> Мне сложно дать оценку этому предложению, но наверняка идея отличная! Предлагаю пока исходить из того, что мы не знаем такой подход и пробовать добавлять коммиты по примеру ментора. Если будут явные проблемы - будем пробовать применять .prettierrc.json или иные варианты.

При всем уважении. 
В прекурсе, в разделе VS Code подробно перечислены все plug-in, которые нужно было установить. В частности в разделе "Розширення Prettier та Formatting Toggle". Я так понимаю, что всем необходимо было их установить. Внешне файл index.html выглядит неотформатированным.  Например, отсутствуют отступы от края для тегов разного уровня (смотри body, html). 
 Мне не сложно сбросить коммит в том виде, который Вы просите, однако я опасаюсь, что с увеличением размера кода, проблема приобретет глобальный масштаб для нашего проекта. 
 Ожидаю Вашего окончательного решения , как  лидера проекта.

2023-03-26 16:53 UTC, O-TYSHCHENKO requested changes
Не могу подтвердить pull request пока есть конфликты. Пожалуйста исправьте конфликт в своей ветке путем "стягивания" с текущей версии на главной ветке.

2023-03-26 17:00 UTC, O-TYSHCHENKO requested changes

2023-03-26 17:00 UTC, O-TYSHCHENKO commented on index.html
> +    <meta charset="UTF-8" />
Предлагаю внести только свою часть кода в <body>, а часть в <head> не вносить в pull request.

2023-03-26 17:45 UTC, closed without merging

2023-03-26 17:45 UTC, O-TYSHCHENKO commented
> > Мне сложно дать оценку этому предложению, но наверняка идея отличная! Предлагаю пока исходить из того, что мы не знаем такой подход и пробовать добавлять коммиты по примеру ментора. Если будут явные проблемы - будем пробовать применять .prettierrc.json или иные варианты.
> 
> При всем уважении. В прекурсе, в разделе VS Code подробно перечислены все plug-in, которые нужно было установить. В частности в разделе "Розширення Prettier та Formatting Toggle". Я так понимаю, что всем необходимо было их установить. Внешне файл index.html выглядит неотформатированным. Например, отсутствуют отступы от края для тегов разного уровня (смотри body, html). Мне не сложно сбросить коммит в том виде, который Вы просите, однако я опасаюсь, что с увеличением размера кода, проблема приобретет глобальный масштаб для нашего проекта. Ожидаю Вашего окончательного решения , как лидера проекта.

Касательно настроек VS Code: у меня настроены расширения Prettier и Formatting согласно рекомендациям лекторов. Но действительно странно, что есть один нюанс при форматировании - тег html и body находятся на одном уровне...внешне вижу только такую проблему форматирования. Есть предположение, что так настроены Prettier и Formatting у многих из команды. Если есть инфа, что нужно изменить в настройках - буду благодарен!

2023-03-26 18:57 UTC, kondyan2022 commented
> > > Мне сложно дать оценку этому предложению, но наверняка идея отличная! Предлагаю пока исходить из того, что мы не знаем такой подход и пробовать добавлять коммиты по примеру ментора. Если будут явные проблемы - будем пробовать применять .prettierrc.json или иные варианты.
> > 
> > 
> > При всем уважении. В прекурсе, в разделе VS Code подробно перечислены все plug-in, которые нужно было установить. В частности в разделе "Розширення Prettier та Formatting Toggle". Я так понимаю, что всем необходимо было их установить. Внешне файл index.html выглядит неотформатированным. Например, отсутствуют отступы от края для тегов разного уровня (смотри body, html). Мне не сложно сбросить коммит в том виде, который Вы просите, однако я опасаюсь, что с увеличением размера кода, проблема приобретет глобальный масштаб для нашего проекта. Ожидаю Вашего окончательного решения , как лидера проекта.
> 
> Касательно настроек VS Code: у меня настроены расширения Prettier и Formatting согласно рекомендациям лекторов. Но действительно странно, что есть один нюанс при форматировании - тег html и body находятся на одном уровне...внешне вижу только такую проблему форматирования. Есть предположение, что так настроены Prettier и Formatting у многих из команды. Если есть инфа, что нужно изменить в настройках - буду благодарен!

Есть предположение, что у вас Prettier не обрабатывал index.html  вообще: т.к. кроме отступа в уровне тегов, убираются пустые строки (например, между body и html. Кроме этого,  Prettier  не совсем корректно закрывает одинарные теги типа img  (например, <meta.... />), об этой особенности говорили наши преподаватели кураторы и говорят, чтобы мы не обращали на это внимание.  
Я предлагаю:
Подключите Prettier (согласно лекций в прекурсе). 
Для проверки, можно внести какие-то изменения в текст index.html и дважды щелкнуть на  Prettier  в правом нижнем углу окна VS Code. 
Обязательно проверьте настройку VS Code: Editor: Format On Save, чтобы текст форматировался при сохранении. Возможно, именно отсутствие этой птички является причиной.. 
Повторюсь, чтобы у всех участников проекта не возникало проблем, нужны одинаковые настройки форматирования. Файл с этими настройками надо включить в проект, и тогда, у всех в проекте будут  одинаковые настройки форматирования. Это позволит избежать коллизий, подобных той, которая возникла при получении изменений в код от меня. 
Собственно говоря - это инфа.

2023-03-28 22:40 UTC, O-TYSHCHENKO commented
> > > > Мне сложно дать оценку этому предложению, но наверняка идея отличная! Предлагаю пока исходить из того, что мы не знаем такой подход и пробовать добавлять коммиты по примеру ментора. Если будут явные проблемы - будем пробовать применять .prettierrc.json или иные варианты.
> > > 
> > > 
> > > При всем уважении. В прекурсе, в разделе VS Code подробно перечислены все plug-in, которые нужно было установить. В частности в разделе "Розширення Prettier та Formatting Toggle". Я так понимаю, что всем необходимо было их установить. Внешне файл index.html выглядит неотформатированным. Например, отсутствуют отступы от края для тегов разного уровня (смотри body, html). Мне не сложно сбросить коммит в том виде, который Вы просите, однако я опасаюсь, что с увеличением размера кода, проблема приобретет глобальный масштаб для нашего проекта. Ожидаю Вашего окончательного решения , как лидера проекта.
> > 
> > 
> > Касательно настроек VS Code: у меня настроены расширения Prettier и Formatting согласно рекомендациям лекторов. Но действительно странно, что есть один нюанс при форматировании - тег html и body находятся на одном уровне...внешне вижу только такую проблему форматирования. Есть предположение, что так настроены Prettier и Formatting у многих из команды. Если есть инфа, что нужно изменить в настройках - буду благодарен!
> 
> Есть предположение, что у вас Prettier не обрабатывал index.html вообще: т.к. кроме отступа в уровне тегов, убираются пустые строки (например, между body и html. Кроме этого, Prettier не совсем корректно закрывает одинарные теги типа img (например, <meta.... />), об этой особенности говорили наши преподаватели кураторы и говорят, чтобы мы не обращали на это внимание. Я предлагаю: Подключите Prettier (согласно лекций в прекурсе). Для проверки, можно внести какие-то изменения в текст index.html и дважды щелкнуть на Prettier в правом нижнем углу окна VS Code. Обязательно проверьте настройку VS Code: Editor: Format On Save, чтобы текст форматировался при сохранении. Возможно, именно отсутствие этой птички является причиной.. Повторюсь, чтобы у всех участников проекта не возникало проблем, нужны одинаковые настройки форматирования. Файл с этими настройками надо включить в проект, и тогда, у всех в проекте будут одинаковые настройки форматирования. Это позволит избежать коллизий, подобных той, которая возникла при получении изменений в код от меня. Собственно говоря - это инфа.

Добавил файл .prettierrc.json в проект! Спасибо!