Added section favorites
O-TYSHCHENKO/food-sta-tp pull request #7
Opened 2023-03-27 09:46 UTC by Nataliia-Katrenko

2023-03-27 22:05 UTC, O-TYSHCHENKO approved these changes

2023-03-28 16:12 UTC, O-TYSHCHENKO requested changes

2023-03-28 16:12 UTC, O-TYSHCHENKO commented on index.html
> +    <section class="favorites container section">
Нет описания классов container и section в .css
Прошу добавить в .css в этом pull request.

2023-03-28 16:14 UTC, O-TYSHCHENKO commented
Не могу подтвердить pull request пока есть конфликты. Пожалуйста исправьте конфликт в своей ветке путем "стягивания" с текущей версии на главной ветке.

2023-03-30 06:18 UTC, kondyan2022 approved these changes

2023-03-30 07:14 UTC, kondyan2022 commented
Наталія, lоброго дня. 
У Вашому коді треба дещо виправити: 
1. В секції повинен бути контейнер, а саме, код секції повинен виглядати таким чином:
```
<section class="favorites">  
   <div class="container">
      .............. код секції................
   </div>
 </section>

``` 
Мушу просити зробити Вас саме так, бо саме такі вимоги до нашого ДЗ та цього проекта.

 2. У Вас не працює форматировщик Prettier. Вам обов'язково потрібно його налаштувати. Для цього зробить наступне:
 - перевірте, чи встановлено у Вас Prettier. Про його встановлення та налаштування є інформація в прекурсі в розділі "Розширення Prettier та Formatting Toggle". 
 - якщо  Prettier  встановлено, треба перевірити, працює він чи ні. Це можливо зробити наступним чином:
                             1. CMD + Shift + P 
                                                 або
                             1. Виділить фрагмент 
                              2. CMD + Shift + P 
 Текст повиннен відформатуватися.
 - якщо форматує,  то треба перевірити налаштування VS Code, а саме: 
 
![image](https://user-images.githubusercontent.com/119456733/228755448-98591950-8119-45b8-817f-05621f9f94f1.png)

після цього: 
-  скопіюйте і збережить ваш код з CSS та HTML файлов окремо, наприклад, у Блокнот. 
- зайдіть в GitHub desktop та видаліть Свою гілку. Перейдіть у гілку main. обновіть данні з репозіторію.
- створить нову гілку та перейдіть в неї
- відкрийте проект в VS Code
- додайте свій код
- зробить commit, а потім Pull Request.

Сподіваюсь, що у Вас все вийде. Зв'яжіться зі мною якщо будуть питання.
Дякую.

З повагою, 
Ян

2023-03-30 07:15 UTC, closed without merging